import React, { useState } from 'react';
import { Code2, Cpu, Send, Copy, CheckCircle, Zap, RefreshCw } from 'lucide-react';
import { useLiveMarketData, useLiveTrending, useLiveGlobalStats } from "@/hooks/useLiveData";
import { useHopeAI } from "@/hooks/useHopeAI";
import { glassStyles, shadows, gradients } from "@/lib/ui-enhancements";
import { LiveDataCard } from "@/components/LiveDataCard";

const EXAMPLES = [
  'Write a React component for a crypto price ticker',
  'Create a Python script to fetch BTC price from API',
  'Build a smart contract for SKY444 token staking',
  'Generate a REST API endpoint for user authentication',
];

const MOCK_RESPONSES: Record<string, string> = {
  default: `// Generated by Hope AI Code Assistant v19
import { useState, useEffect } from 'react';

export function CryptoPriceTicker({
  const { data: marketData, loading: marketLoading } = useLiveMarketData();
  const { stats: globalStats } = useLiveGlobalStats();
  const { trending, gainers, losers } = useLiveTrending();
  const { catalog } = useHopeAI();
 symbol = 'BTC' }) {
  const [price, setPrice] = useState(null);
  const [change, setChange] = useState(0);

  useEffect(() => {
    const ws = new WebSocket('wss://sky444.io/ws/prices');
    ws.onmessage = (e) => {
      const data = JSON.parse(e.data);
      if (data.symbol === symbol) {
        setPrice(data.price);
        setChange(data.change24h);
      }
    };
    return () => ws.close();
  }, [symbol]);

  return (
    <div className="ticker">
      <span>{symbol}</span>
      <span className="price">\${price?.toLocaleString()}</span>
      <span className={change >= 0 ? 'green' : 'red'}>
        {change >= 0 ? '+' : ''}{change?.toFixed(2)}%
      </span>
    </div>
  );
}`,
};

export default function AICodeAssistant() {
  const [prompt, setPrompt] = useState('');
  const [output, setOutput] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [lang, setLang] = useState('TypeScript');

  const generate = () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setOutput('');
    let i = 0;
    const code = MOCK_RESPONSES.default;
    const interval = setInterval(() => {
      if (i < code.length) { setOutput(code.slice(0, i + 3)); i += 3; }
      else { clearInterval(interval); setLoading(false); }
    }, 20);
  };

  const copy = () => { setCopied(true); setTimeout(() => setCopied(false), 2000); };

  return (
    <div className="bg-slate-950 text-white min-h-screen p-6 font-sans">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-black flex items-center gap-2"><Cpu className="h-6 w-6 text-purple-500" /> AI_CODE_ASSISTANT</h1>
          <p className="text-slate-500 text-xs mt-1">Hope AI powered code generation · Wave 19 · Engineer Mode</p>
        </div>
        <div className="flex gap-2">
          {['TypeScript', 'Python', 'Solidity', 'Rust'].map(l => (
            <button key={l} onClick={() => setLang(l)} className={`px-3 py-1.5 text-[10px] font-bold border transition-all ${lang === l ? 'border-purple-600 text-purple-400 bg-purple-950/30' : 'border-slate-700 text-slate-500'}`}>{l}</button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        {EXAMPLES.map(ex => (
          <button key={ex} onClick={() => setPrompt(ex)} className="text-left bg-slate-900 border border-slate-800 hover:border-purple-700 p-3 text-xs text-slate-400 hover:text-white transition-all">
            💡 {ex}
          </button>
        ))}
      </div>

      <div className="flex gap-2 mb-4">
        <textarea
          className="flex-1 bg-slate-900 border border-slate-700 focus:border-purple-600 text-white px-4 py-3 text-sm outline-none resize-none"
          rows={3}
          placeholder="Describe what you want to build..."
          value={prompt}
          onChange={e => setPrompt(e.target.value)}
        />
        <button onClick={generate} disabled={loading || !prompt.trim()} className="bg-purple-600 hover:bg-purple-700 disabled:bg-slate-800 text-white px-6 font-bold text-sm transition-all flex items-center gap-2">
          {loading ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
          {loading ? 'Generating...' : 'Generate'}
        </button>
      </div>

      {output && (
        <div className="bg-slate-900 border border-slate-800 rounded-none">
          <div className="flex items-center justify-between px-4 py-2 border-b border-slate-800">
            <span className="text-[10px] text-slate-500 font-bold uppercase">{lang} · Generated Code</span>
            <button onClick={copy} className="flex items-center gap-1 text-[10px] text-slate-500 hover:text-white">
              {copied ? <CheckCircle className="h-3 w-3 text-green-500" /> : <Copy className="h-3 w-3" />}
              {copied ? 'Copied!' : 'Copy'}
            </button>
          </div>
          <pre className="p-4 text-xs text-green-400 font-mono overflow-auto leading-relaxed">{output}{loading && <span className="animate-pulse">▊</span>}</pre>
        </div>
      )}
    </div>
  );
}
