import { useState } from "react";
import { motion } from "framer-motion";
import {
  Code2,
  Zap,
  Copy,
  Play,
  Download,
  RefreshCw,
  ChevronRight,
  Terminal,
  FileCode,
  Sparkles,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

const TEMPLATES = [
  {
    id: 1,
    name: "ERC-20 Token",
    lang: "Solidity",
    desc: "Deploy your own SKY4444-style token",
    emoji: "🪙",
  },
  {
    id: 2,
    name: "NFT Contract",
    lang: "Solidity",
    desc: "ERC-721 with royalties and whitelist",
    emoji: "🎨",
  },
  {
    id: 3,
    name: "React DApp",
    lang: "TypeScript",
    desc: "Web3 frontend with wallet connect",
    emoji: "⚛️",
  },
  {
    id: 4,
    name: "Trading Bot",
    lang: "Python",
    desc: "Automated crypto trading strategy",
    emoji: "🤖",
  },
  {
    id: 5,
    name: "REST API",
    lang: "Node.js",
    desc: "Express API with JWT auth",
    emoji: "🔌",
  },
  {
    id: 6,
    name: "Smart Contract Audit",
    lang: "Solidity",
    desc: "Security audit checklist",
    emoji: "🔍",
  },
];

const EXAMPLE_CODE: Record<string, string> = {
  "ERC-20 Token": `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract SKY4444Token is ERC20, Ownable {
    uint256 public constant MAX_SUPPLY = 444_444_444 * 10**18;
    
    constructor() ERC20("SKY4444", "SKY4444") Ownable(msg.sender) {
        _mint(msg.sender, 44_444_444 * 10**18);
    }
    
    function mint(address to, uint256 amount) external onlyOwner {
        require(totalSupply() + amount <= MAX_SUPPLY, "Exceeds max supply");
        _mint(to, amount);
    }
    
    function burn(uint256 amount) external {
        _burn(msg.sender, amount);
    }
}`,
  "NFT Contract": `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract ShadowNFT is ERC721, Ownable {
    uint256 private _tokenIds;
    uint256 public mintPrice = 0.044 ether;
    uint256 public maxSupply = 4444;
    mapping(address => bool) public whitelist;
    
    constructor() ERC721("ShadowNFT", "SNFT") Ownable(msg.sender) {}
    
    function mint() external payable {
        require(msg.value >= mintPrice, "Insufficient payment");
        require(_tokenIds < maxSupply, "Sold out");
        _tokenIds++;
        _safeMint(msg.sender, _tokenIds);
    }
    
    function addToWhitelist(address[] calldata addresses) external onlyOwner {
        for (uint i = 0; i < addresses.length; i++) {
            whitelist[addresses[i]] = true;
        }
    }
}`,
  "React DApp": `import { useState } from 'react';
import { ethers } from 'ethers';

export default function ShadowDApp() {
  const [account, setAccount] = useState<string>('');
  const [balance, setBalance] = useState<string>('');
  
  const connectWallet = async () => {
    if (!window.ethereum) {
      alert('Install MetaMask!');
      return;
    }
    const provider = new ethers.BrowserProvider(window.ethereum);
    const accounts = await provider.send('eth_requestAccounts', []);
    const signer = await provider.getSigner();
    const bal = await provider.getBalance(accounts[0]);
    setAccount(accounts[0]);
    setBalance(ethers.formatEther(bal));
  };
  
  return (
    <div className="p-8">
      <h1>ShadowChat DApp</h1>
      {account ? (
        <div>
          <p>Connected: {account}</p>
          <p>Balance: {balance} ETH</p>
        </div>
      ) : (
        <button onClick={connectWallet}>Connect Wallet</button>
      )}
    </div>
  );
}`,
};

const LANGUAGES = ["All", "Solidity", "TypeScript", "Python", "Node.js"];

export default function ShadowAICode() {
  const [prompt, setPrompt] = useState("");
  const [selectedTemplate, setSelectedTemplate] = useState<
    (typeof TEMPLATES)[0] | null
  >(null);
  const [code, setCode] = useState(EXAMPLE_CODE["ERC-20 Token"]);
  const [generating, setGenerating] = useState(false);
  const [langFilter, setLangFilter] = useState("All");

  const generate = async () => {
    if (!prompt.trim()) {
      toast.error("Enter a prompt first");
      return;
    }
    setGenerating(true);
    await new Promise(r => setTimeout(r, 1500));
    setCode(`// AI-Generated Code for: "${prompt}"
// Generated by ShadowAI Code Assistant
// SKY4444 Platform · ${new Date().toLocaleDateString()}

pragma solidity ^0.8.20;

// Your custom contract based on: ${prompt}
contract CustomContract {
    address public owner;
    mapping(address => uint256) public balances;
    
    event Transfer(address indexed from, address indexed to, uint256 amount);
    
    constructor() {
        owner = msg.sender;
    }
    
    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }
    
    function deposit() external payable {
        balances[msg.sender] += msg.value;
    }
    
    function withdraw(uint256 amount) external {
        require(balances[msg.sender] >= amount, "Insufficient balance");
        balances[msg.sender] -= amount;
        payable(msg.sender).transfer(amount);
        emit Transfer(address(this), msg.sender, amount);
    }
}`);
    setGenerating(false);
    toast.success("✅ Code generated by ShadowAI!");
  };

  const filtered =
    langFilter === "All"
      ? TEMPLATES
      : TEMPLATES.filter(t => t.lang === langFilter);

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-black flex items-center gap-2">
            <Code2 className="h-6 w-6 text-green-400" />
            AI Code Assistant
          </h1>
          <p className="text-sm text-muted-foreground">
            Generate smart contracts, DApps, bots, and APIs with AI
          </p>
        </div>
        <Badge className="bg-green-500/10 text-green-400 border-green-500/20 font-bold">
          ⚡ AI
        </Badge>
      </div>

      {/* Prompt Input */}
      <Card className="border-green-500/20 bg-green-900/5">
        <CardContent className="py-3 px-4 space-y-2">
          <p className="text-xs font-bold text-muted-foreground">
            DESCRIBE WHAT YOU WANT TO BUILD
          </p>
          <div className="flex gap-2">
            <textarea
              value={prompt}
              onChange={e => setPrompt(e.target.value)}
              placeholder="e.g. Create a staking contract that rewards SKY4444 holders with 12% APY..."
              className="flex-1 h-16 rounded-xl border border-border bg-background px-3 py-2 text-xs resize-none focus:outline-none focus:border-green-500/50"
            />
            <Button
              className="h-full px-4 text-xs bg-green-600 text-white border-0 font-bold"
              onClick={generate}
              disabled={generating}
            >
              {generating ? (
                <RefreshCw className="h-4 w-4 animate-spin" />
              ) : (
                <Sparkles className="h-4 w-4" />
              )}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Templates */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <p className="text-xs font-bold text-muted-foreground">
            STARTER TEMPLATES
          </p>
          <div className="flex gap-1">
            {LANGUAGES.map(l => (
              <button
                key={l}
                onClick={() => setLangFilter(l)}
                className={`px-2.5 py-1 rounded-full text-xs font-medium transition-colors ${langFilter === l ? "bg-green-600 text-white" : "bg-muted text-muted-foreground"}`}
              >
                {l}
              </button>
            ))}
          </div>
        </div>
        <div className="grid grid-cols-3 gap-2">
          {filtered.map(template => (
            <Card
              key={template.id}
              className={`border cursor-pointer transition-all ${selectedTemplate?.id === template.id ? "border-green-500/40 bg-green-900/10" : "border-border/50 hover:border-green-500/20"}`}
              onClick={() => {
                setSelectedTemplate(template);
                setCode(
                  EXAMPLE_CODE[template.name] ||
                    `// ${template.name} template\n// Language: ${template.lang}`
                );
              }}
            >
              <CardContent className="py-2.5 px-3">
                <p className="text-base mb-1">{template.emoji}</p>
                <p className="font-bold text-xs leading-tight">
                  {template.name}
                </p>
                <Badge className="text-xs bg-muted text-muted-foreground mt-0.5">
                  {template.lang}
                </Badge>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* Code Editor */}
      <Card className="border-border/50">
        <CardContent className="py-0 px-0">
          <div className="flex items-center justify-between px-4 py-2 border-b border-border/50">
            <div className="flex items-center gap-2">
              <Terminal className="h-4 w-4 text-green-400" />
              <p className="text-xs font-bold">
                {selectedTemplate?.name || "ERC-20 Token"}.sol
              </p>
              <Badge className="text-xs bg-muted text-muted-foreground">
                {selectedTemplate?.lang || "Solidity"}
              </Badge>
            </div>
            <div className="flex gap-1.5">
              <Button
                size="sm"
                variant="ghost"
                className="h-7 text-xs"
                onClick={() => {
                  navigator.clipboard?.writeText(code);
                  toast.success("Copied!");
                }}
              >
                <Copy className="h-3.5 w-3.5 mr-1" />
                Copy
              </Button>
              <Button
                size="sm"
                className="h-7 text-xs bg-green-600 text-white border-0 font-bold"
                onClick={() => toast.success("🚀 Deploying to testnet...")}
              >
                <Play className="h-3.5 w-3.5 mr-1" />
                Deploy
              </Button>
            </div>
          </div>
          <pre className="p-4 text-xs font-mono text-green-300 bg-gray-950 rounded-b-xl overflow-x-auto max-h-72 overflow-y-auto leading-relaxed">
            {generating ? (
              <motion.span
                animate={{ opacity: [1, 0.3, 1] }}
                transition={{ repeat: Infinity, duration: 0.8 }}
              >
                Generating code...
              </motion.span>
            ) : (
              code
            )}
          </pre>
        </CardContent>
      </Card>

      <div className="grid grid-cols-3 gap-2">
        {[
          { label: "Contracts Generated", value: "4,444", emoji: "📄" },
          { label: "Languages Supported", value: "12", emoji: "💻" },
          { label: "Gas Optimized", value: "100%", emoji: "⛽" },
        ].map(s => (
          <Card key={s.label} className="border-border/50 text-center">
            <CardContent className="pt-2 pb-2">
              <p className="text-base">{s.emoji}</p>
              <p className="font-black text-xs text-green-400">{s.value}</p>
              <p className="text-xs text-muted-foreground">{s.label}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
