import { useState } from "react";
import { motion } from "framer-motion";
import {
  FlaskConical,
  Brain,
  Zap,
  Code,
  Image,
  Music,
  Video,
  MessageSquare,
  TrendingUp,
  Shield,
  Star,
  Play,
  Settings,
  ChevronRight,
  CheckCircle,
  RefreshCw,
  Sparkles,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

const AI_MODELS = [
  {
    id: "shadow-gpt",
    name: "ShadowGPT-4",
    type: "Text",
    tokens: "128K",
    speed: "Fast",
    accuracy: "98%",
    cost: "0.001 SKY/req",
    icon: MessageSquare,
    color: "text-blue-400",
    bg: "bg-blue-500/10",
  },
  {
    id: "shadow-vision",
    name: "ShadowVision",
    type: "Image",
    tokens: "—",
    speed: "Medium",
    accuracy: "94%",
    cost: "0.01 SKY/req",
    icon: Image,
    color: "text-purple-400",
    bg: "bg-purple-500/10",
  },
  {
    id: "shadow-code",
    name: "ShadowCode",
    type: "Code",
    tokens: "64K",
    speed: "Fast",
    accuracy: "96%",
    cost: "0.002 SKY/req",
    icon: Code,
    color: "text-green-400",
    bg: "bg-green-500/10",
  },
  {
    id: "shadow-trade",
    name: "ShadowTradeAI",
    type: "Finance",
    tokens: "32K",
    speed: "Ultra",
    accuracy: "91%",
    cost: "0.005 SKY/req",
    icon: TrendingUp,
    color: "text-yellow-400",
    bg: "bg-yellow-500/10",
  },
  {
    id: "shadow-music",
    name: "ShadowMusicGen",
    type: "Audio",
    tokens: "—",
    speed: "Slow",
    accuracy: "89%",
    cost: "0.05 SKY/req",
    icon: Music,
    color: "text-pink-400",
    bg: "bg-pink-500/10",
  },
  {
    id: "shadow-guard",
    name: "ShadowGuard",
    type: "Safety",
    tokens: "16K",
    speed: "Ultra",
    accuracy: "99%",
    cost: "0.0005 SKY/req",
    icon: Shield,
    color: "text-red-400",
    bg: "bg-red-500/10",
  },
];

const AGENTS = [
  {
    name: "TradingBot Alpha",
    model: "ShadowTradeAI",
    status: "running",
    tasks: 142,
    earnings: "$84.20",
    uptime: "99.8%",
  },
  {
    name: "ContentModerator",
    model: "ShadowGuard",
    status: "running",
    tasks: 8420,
    earnings: "$12.60",
    uptime: "100%",
  },
  {
    name: "NFT Rarity Scorer",
    model: "ShadowVision",
    status: "paused",
    tasks: 320,
    earnings: "$4.80",
    uptime: "—",
  },
  {
    name: "Code Reviewer",
    model: "ShadowCode",
    status: "running",
    tasks: 89,
    earnings: "$2.40",
    uptime: "97.2%",
  },
];

export default function ShadowAILab() {
  const [tab, setTab] = useState<
    "models" | "playground" | "agents" | "finetune"
  >("models");
  const [selectedModel, setSelectedModel] = useState("shadow-gpt");
  const [prompt, setPrompt] = useState("");
  const [output, setOutput] = useState("");
  const [running, setRunning] = useState(false);

  const runModel = async () => {
    if (!prompt.trim()) {
      toast.error("Enter a prompt");
      return;
    }
    setRunning(true);
    setOutput("");
    await new Promise(r => setTimeout(r, 1800));
    const model = AI_MODELS.find(m => m.id === selectedModel);
    const responses: Record<string, string> = {
      "shadow-gpt": `Based on your prompt "${prompt.slice(0, 30)}...", here is a comprehensive analysis:\n\nShadowChat's AI ecosystem represents a paradigm shift in decentralized intelligence. The SKY4444 token serves as the utility backbone, enabling permissionless access to 6 specialized AI models. Each inference is recorded on-chain, creating an immutable audit trail for compliance and governance.\n\nKey insights:\n1. AI-powered trading signals achieve 91% accuracy on backtested data\n2. Content moderation reduces harmful content by 99.7%\n3. NFT rarity scoring increases collection value by 24% on average\n\nRecommendation: Deploy the TradingBot Alpha agent with $1,000 initial capital for optimal risk-adjusted returns.`,
      "shadow-code": `// Generated by ShadowCode AI\n// Prompt: ${prompt.slice(0, 40)}\n\nconst shadowContract = {\n  name: "SKY4444",\n  symbol: "SKY",\n  totalSupply: 1_000_000_000,\n  decimals: 18,\n  \n  transfer: async (to: string, amount: bigint) => {\n    // Validate recipient\n    if (!isValidAddress(to)) throw new Error("Invalid address");\n    // Apply 0.1% burn on transfer\n    const burnAmount = amount / 1000n;\n    const netAmount = amount - burnAmount;\n    await burn(burnAmount);\n    return await _transfer(to, netAmount);\n  }\n};\n\nexport default shadowContract;`,
      "shadow-trade": `📊 TRADING SIGNAL ANALYSIS\n\nAsset: SKY4444/USDT\nSignal: STRONG BUY (94% confidence)\nEntry: $0.0842\nTarget 1: $0.0950 (+12.8%)\nTarget 2: $0.1100 (+30.6%)\nStop Loss: $0.0780 (-7.4%)\n\nRationale:\n• RSI(14) = 42 — oversold territory\n• MACD bullish crossover forming\n• Volume 3x above 20-day average\n• ICO momentum + exchange listing catalyst\n\nRisk/Reward: 1:4.1 — Excellent setup`,
    };
    setOutput(
      responses[selectedModel] ||
        `ShadowAI response for "${prompt.slice(0, 30)}...":\n\nProcessed ${Math.floor(Math.random() * 1000 + 500)} tokens in ${(Math.random() * 0.8 + 0.2).toFixed(2)}s. Cost: ${model?.cost || "0.001 SKY"}.`
    );
    setRunning(false);
  };

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-black flex items-center gap-2">
            <FlaskConical className="h-6 w-6 text-cyan-400" />
            ShadowAI Lab
          </h1>
          <p className="text-sm text-muted-foreground">
            AI research lab — test models, deploy agents, fine-tune, and build
            AI-powered workflows
          </p>
        </div>
        <Badge className="bg-cyan-500/10 text-cyan-400 border-cyan-500/20 text-xs">
          6 Models Available
        </Badge>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-2">
        {[
          { label: "API Calls Today", value: "84.2K", color: "text-cyan-400" },
          { label: "Active Agents", value: "3", color: "text-green-400" },
          { label: "Avg Accuracy", value: "94.5%", color: "text-yellow-400" },
          { label: "SKY Earned", value: "142 SKY", color: "text-blue-400" },
        ].map(s => (
          <Card key={s.label} className="border-border/50 text-center">
            <CardContent className="py-3 px-2">
              <p className={`font-black text-lg ${s.color}`}>{s.value}</p>
              <p className="text-xs text-muted-foreground">{s.label}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Tabs */}
      <div className="flex gap-2 flex-wrap">
        {(
          [
            ["models", "🧠 Models"],
            ["playground", "🎮 Playground"],
            ["agents", "🤖 Agents"],
            ["finetune", "⚙️ Fine-Tune"],
          ] as const
        ).map(([t, label]) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors ${tab === t ? "bg-cyan-600 text-white" : "bg-muted text-muted-foreground"}`}
          >
            {label}
          </button>
        ))}
      </div>

      {/* Models */}
      {tab === "models" && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {AI_MODELS.map((model, i) => {
            const Icon = model.icon;
            return (
              <motion.div
                key={model.id}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.06 }}
              >
                <Card className="border-border/50 hover:border-cyan-500/20 transition-all">
                  <CardContent className="py-4 px-4 space-y-3">
                    <div className="flex items-center gap-3">
                      <div
                        className={`h-10 w-10 rounded-xl ${model.bg} flex items-center justify-center shrink-0`}
                      >
                        <Icon className={`h-5 w-5 ${model.color}`} />
                      </div>
                      <div className="flex-1">
                        <p className="font-black text-sm">{model.name}</p>
                        <Badge className="text-xs bg-muted text-muted-foreground border-0">
                          {model.type}
                        </Badge>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-2 text-xs">
                      <div>
                        <span className="text-muted-foreground">
                          Accuracy:{" "}
                        </span>
                        <span className="font-bold text-green-400">
                          {model.accuracy}
                        </span>
                      </div>
                      <div>
                        <span className="text-muted-foreground">Speed: </span>
                        <span className="font-bold">{model.speed}</span>
                      </div>
                      <div>
                        <span className="text-muted-foreground">Context: </span>
                        <span className="font-bold">{model.tokens}</span>
                      </div>
                      <div>
                        <span className="text-muted-foreground">Cost: </span>
                        <span className="font-bold text-yellow-400">
                          {model.cost}
                        </span>
                      </div>
                    </div>
                    <Button
                      size="sm"
                      className="w-full h-8 text-xs bg-cyan-600 text-white border-0 font-bold"
                      onClick={() => {
                        setSelectedModel(model.id);
                        setTab("playground");
                        toast.info(`Switched to ${model.name}`);
                      }}
                    >
                      <Play className="h-3.5 w-3.5 mr-1" />
                      Try in Playground
                    </Button>
                  </CardContent>
                </Card>
              </motion.div>
            );
          })}
        </div>
      )}

      {/* Playground */}
      {tab === "playground" && (
        <div className="space-y-4">
          <div className="flex gap-2 flex-wrap">
            {AI_MODELS.map(m => (
              <button
                key={m.id}
                onClick={() => setSelectedModel(m.id)}
                className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors ${selectedModel === m.id ? "bg-cyan-600 text-white" : "bg-muted text-muted-foreground"}`}
              >
                {m.name}
              </button>
            ))}
          </div>
          <Card className="border-cyan-500/20 bg-cyan-900/5">
            <CardContent className="py-5 px-5 space-y-4">
              <textarea
                value={prompt}
                onChange={e => setPrompt(e.target.value)}
                placeholder="Enter your prompt here..."
                className="w-full h-24 px-4 py-3 rounded-xl bg-muted text-sm border border-border/50 focus:outline-none focus:border-cyan-500/40 resize-none"
              />
              <Button
                className="w-full h-10 bg-cyan-600 text-white border-0 font-bold text-sm"
                onClick={runModel}
                disabled={running}
              >
                {running ? (
                  <>
                    <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                    Running...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4 mr-2" />
                    Run Model
                  </>
                )}
              </Button>
              {output && (
                <motion.div
                  initial={{ opacity: 0, y: 6 }}
                  animate={{ opacity: 1, y: 0 }}
                >
                  <div className="bg-muted rounded-xl p-4">
                    <p className="text-xs font-bold text-cyan-400 mb-2">
                      Output:
                    </p>
                    <pre className="text-xs text-foreground whitespace-pre-wrap font-mono leading-relaxed">
                      {output}
                    </pre>
                  </div>
                </motion.div>
              )}
            </CardContent>
          </Card>
        </div>
      )}

      {/* Agents */}
      {tab === "agents" && (
        <div className="space-y-3">
          {AGENTS.map((agent, i) => (
            <motion.div
              key={agent.name}
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.06 }}
            >
              <Card className="border-border/50 hover:border-cyan-500/20 transition-all">
                <CardContent className="py-3 px-4 flex items-center gap-3">
                  <div
                    className={`h-9 w-9 rounded-xl flex items-center justify-center shrink-0 ${agent.status === "running" ? "bg-green-500/10" : "bg-muted"}`}
                  >
                    <Brain
                      className={`h-4.5 w-4.5 ${agent.status === "running" ? "text-green-400" : "text-muted-foreground"}`}
                    />
                  </div>
                  <div className="flex-1">
                    <p className="font-bold text-sm">{agent.name}</p>
                    <p className="text-xs text-muted-foreground">
                      {agent.model} · {agent.tasks.toLocaleString()} tasks ·
                      Uptime: {agent.uptime}
                    </p>
                  </div>
                  <div className="text-right shrink-0 space-y-1">
                    <p className="font-black text-sm text-green-400">
                      {agent.earnings}
                    </p>
                    <Badge
                      className={`text-xs border-0 ${agent.status === "running" ? "bg-green-500/10 text-green-400" : "bg-muted text-muted-foreground"}`}
                    >
                      {agent.status}
                    </Badge>
                  </div>
                  <Button
                    size="sm"
                    className={`h-7 px-3 text-xs border-0 font-bold shrink-0 ${agent.status === "running" ? "bg-red-600 text-white" : "bg-green-600 text-white"}`}
                    onClick={() =>
                      toast.success(
                        `${agent.status === "running" ? "Paused" : "Started"} ${agent.name}`
                      )
                    }
                  >
                    {agent.status === "running" ? "Pause" : "Start"}
                  </Button>
                </CardContent>
              </Card>
            </motion.div>
          ))}
          <Button
            className="w-full h-10 bg-cyan-600 text-white border-0 font-bold text-sm"
            onClick={() => toast.info("Agent builder coming soon!")}
          >
            <Brain className="h-4 w-4 mr-2" />
            Deploy New Agent
          </Button>
        </div>
      )}

      {/* Fine-Tune */}
      {tab === "finetune" && (
        <div className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Fine-tune ShadowAI models on your own data for specialized tasks.
          </p>
          {[
            {
              title: "Upload Training Data",
              desc: "JSONL format, up to 100MB",
              status: "ready",
              action: "Upload",
            },
            {
              title: "Select Base Model",
              desc: "ShadowGPT-4 recommended",
              status: "ready",
              action: "Select",
            },
            {
              title: "Configure Hyperparams",
              desc: "Epochs, learning rate, batch",
              status: "ready",
              action: "Config",
            },
            {
              title: "Start Fine-Tuning",
              desc: "Est. 2-4 hours, 500 SKY cost",
              status: "disabled",
              action: "Start",
            },
          ].map((step, i) => (
            <Card key={step.title} className="border-border/50">
              <CardContent className="py-3 px-4 flex items-center gap-3">
                <div
                  className={`h-7 w-7 rounded-full flex items-center justify-center shrink-0 text-xs font-black ${step.status === "disabled" ? "bg-muted text-muted-foreground" : "bg-cyan-600 text-white"}`}
                >
                  {i + 1}
                </div>
                <div className="flex-1">
                  <p className="font-bold text-sm">{step.title}</p>
                  <p className="text-xs text-muted-foreground">{step.desc}</p>
                </div>
                <Button
                  size="sm"
                  className={`h-7 px-3 text-xs border-0 font-bold shrink-0 ${step.status === "disabled" ? "bg-muted text-muted-foreground" : "bg-cyan-600 text-white"}`}
                  disabled={step.status === "disabled"}
                  onClick={() => toast.info(`${step.action} step initiated`)}
                >
                  {step.action}
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
